import { Context, Schema } from 'koishi';
export declare const name = "qq-group-manager";
export declare const inject: {
    optional: string[];
};
export interface Config {
    command: string;
    platformFilter: string[];
    responseStyle: 'plain' | 'meow';
    dryRun: boolean;
    enableSelfGag: boolean;
    enableUnauthorizedMutePunish: boolean;
    unauthorizedMuteAttemptThreshold: number;
    unauthorizedMuteWindowMinutes: number;
    unauthorizedMutePunishMinMinutes: number;
    unauthorizedMutePunishMaxMinutes: number;
    enableAiReply: boolean;
    aiProvider: 'openai-compatible' | 'gemini';
    aiApiKey: string;
    aiBaseUrl: string;
    aiModel: string;
    aiAgentName: string;
    aiSystemPrompt: string;
    aiActivePersona: string;
    aiPersonas: AIPersona[];
    aiReplyMode: 'threshold' | 'random' | 'hybrid';
    aiMessageThreshold: number;
    aiRandomReplyProbability: number;
    aiMinReplyIntervalSeconds: number;
    aiContextWindow: number;
    aiTemperature: number;
    aiMaxOutputTokens: number;
    aiEnableImageRecognition: boolean;
    aiImageMaxCount: number;
    aiIgnoreCommandMessage: boolean;
    aiEnableDirectMentionTrigger: boolean;
    aiEnableFollowupAfterMention: boolean;
    aiFollowupWindowSeconds: number;
    aiFollowupMaxTurns: number;
    aiOwnerPlatform: string;
    aiOwnerUserId: string;
    aiHomePlatform: string;
    aiHomeUserId: string;
    aiInterestMinScore: number;
    aiInterestContextWindow: number;
    enableRepeater: boolean;
    repeaterThreshold: number;
    repeaterCooldownSeconds: number;
    repeaterEnableGetMsgRefetch: boolean;
    enableJoinRequestReview: boolean;
    joinRequestReviewTtlMinutes: number;
    pendingJoinFileName: string;
    bannedWords: string[];
    strongKeywords: string[];
    blockCardMessage: boolean;
    blockForwardMessage: boolean;
    autoDeleteViolation: boolean;
    sendViolationNotice: boolean;
    enableAutoMute: boolean;
    autoMuteViolationThreshold: number;
    autoMuteMinutes: number;
    enableAutoKick: boolean;
    autoKickViolationThreshold: number;
    autoViolationWindowMinutes: number;
    enableMemory: boolean;
    memoryFileName: string;
    memoryInAi: boolean;
    groupRules: GroupRule[];
    allowedUserIds: string[];
    allowGroupOwner: boolean;
    allowGroupAdmin: boolean;
    requireBotOwnerForAdmin: boolean;
    allowAdminBypassWhitelistMute: boolean;
    logCommandResult: boolean;
    logAuthCheck: boolean;
}
export interface AIPersona {
    id: string;
    selfName: string;
    prompt: string;
}
export interface GroupRule {
    guildId: string;
    enableAiReply?: boolean;
    bannedWords: string[];
    strongKeywords?: string[];
    blockCardMessage: boolean;
    blockForwardMessage: boolean;
    autoDeleteViolation: boolean;
    sendViolationNotice: boolean;
    autoMuteEnabled?: boolean;
    autoMuteThreshold?: number;
    autoMuteMinutes?: number;
    autoKickEnabled?: boolean;
    autoKickThreshold?: number;
    autoViolationWindowMinutes?: number;
    enableJoinRequestReview?: boolean;
}
export declare const Config: Schema<Config>;
export declare function apply(ctx: Context, config: Config): void;
