import { Context, Service, Session } from 'koishi';
import type { Config } from './index';
import type { ActionResult, AuthorizationResult, MuteParseResult } from './types';
declare module 'koishi' {
    interface Context {
        nestimQqGroupManager: QQGroupManagerService;
    }
}
export declare class QQGroupManagerService extends Service {
    ctx: Context;
    config: Config;
    private _logger;
    private unauthorizedMuteAttempts;
    private menuPairings;
    private aiBuffers;
    private aiCounters;
    private aiLastReplyAt;
    private aiInFlight;
    private aiHandledEvents;
    private aiFollowups;
    private aiUserMemory;
    private repeatStates;
    private aiTopicMemory;
    private pendingJoinRequests;
    private pendingJoinRequestFlags;
    private violationRecords;
    constructor(ctx: Context, config: Config);
    isPlatformAllowed(platform?: string): boolean;
    private sessionTag;
    private styleText;
    private escapeHtml;
    private collectCategories;
    private resolveMenuCategory;
    private pairingKey;
    armMenuPairing(session?: Session, ttlMs?: number): void;
    private getMessageText;
    private aiGroupKey;
    private resolveAiEnabled;
    private extractAiMessageText;
    private getDisplayName;
    private isHomeUser;
    private rememberUser;
    private getFollowupSession;
    private tokenizeTopic;
    private scoreTopicRelevance;
    private startFollowupSession;
    private bumpFollowupSession;
    private shouldContinueFollowup;
    private getActivePersona;
    private getActiveAgentName;
    private getActiveSystemPrompt;
    private containsAgentName;
    private isMentionBot;
    private isCommandLikeMessage;
    private isDuplicateAiEvent;
    private pushAiRecord;
    private appendAiContextNote;
    private shouldTriggerAiReply;
    private parseInterestDecision;
    private buildInterestContextPrompt;
    private decideInterestByOpenAI;
    private decideInterestByGemini;
    private shouldReplyByInterest;
    private buildAiUserPrompt;
    private normalizeAiOutput;
    private sanitizeAiOutputForSend;
    private splitAiReplyParts;
    private waitHumanLikeDelay;
    private isAddressingOtherThanBot;
    private extractAiImageUrls;
    private callOpenAiCompatible;
    private callGemini;
    private extractImageUrls;
    private extractMessageImageUrls;
    private extractImageFingerprintKeys;
    private normalizeRepeatText;
    private buildRepeatPayload;
    private parseCqImageParams;
    private extractImageRefsFromRawMessage;
    private extractImageSegmentsFromRawMessage;
    private extractImageSendRefs;
    private fetchMessageImagePayload;
    private sendImageRef;
    private handleRepeater;
    private callOpenAiCompatibleWithImages;
    private generateAiReply;
    private maybeReplyWithAi;
    private fetchOneBotStatus;
    private fetchOnlineClientsCount;
    private formatRssKbToMb;
    private fetchProcessUsageByHints;
    private fetchDockerUsageByHints;
    private fetchLlbotClientUsage;
    private fetchQqClientUsage;
    private handleMenuPairing;
    private getPuppeteer;
    private formatBytes;
    private sampleCpuUsage;
    renderStatusCard(session?: Session): Promise<string>;
    private renderCategoryHtml;
    renderMenu(keyword?: string, session?: Session): Promise<string>;
    private logAuth;
    logCommandResult(command: string, result: ActionResult, session?: Session, extra?: Record<string, unknown>): void;
    authorizeCommand(command: string, session?: Session): Promise<AuthorizationResult>;
    authorize(session?: Session): Promise<AuthorizationResult>;
    canUseAdminCommand(session?: Session): Promise<AuthorizationResult>;
    private isBotOwnerInGroup;
    private resolveMemberRole;
    private normalizeRole;
    private parseTargetId;
    private randomMinutes;
    private extractAtIds;
    private parseDurationToken;
    private extractMuteTokens;
    private looksLikeMemberInGroup;
    parseMuteArguments(session?: Session): Promise<MuteParseResult>;
    private getMemoryFilePath;
    private readMemoryFile;
    private writeMemoryFile;
    private extractMemoryBlocks;
    private saveMemoryToFile;
    private searchMemory;
    private decoratePromptWithMemory;
    private handleMemoryCommand;
    private isImageSendableUrl;
    describeImageMessage(session?: Session): {
        hasCqImage: boolean;
        rawCq: string[];
        elementImages: any[];
        extractableUrls: string[];
    };
    private logImageDebug;
    private isPrivilegedUser;
    private recordUnauthorizedMuteAttempt;
    private isRegularMember;
    shouldSelfGag(session?: Session, target?: string): Promise<boolean>;
    selfGag(session: Session, reason?: string): Promise<ActionResult>;
    punishUnauthorizedMuteAttempt(session?: Session, target?: string): Promise<ActionResult | null>;
    private toGroupId;
    private getOneBotApi;
    private extractTextForFilter;
    private hasTextContent;
    private hasImageOrFace;
    private hasCardMessage;
    private hasForwardMessage;
    private normalizeGuildId;
    private resolveModerationPolicy;
    private detectViolation;
    private deleteMessage;
    private shouldExemptViolationPunish;
    private recordViolation;
    private clearViolationRecord;
    private autoModerationPunish;
    private handleGroupModeration;
    private cleanupPendingJoinRequests;
    private generateJoinRequestCode;
    private parseJoinRequestReviewText;
    private handleJoinRequestReviewMessage;
    private resolveJoinReviewEnabled;
    private fetchStrangerInfo;
    private buildJoinRequestPrompt;
    private handleGuildMemberRequest;
    reviewJoinRequestDecision(session: Session, code: string, approve: boolean, reason?: string): Promise<ActionResult>;
    formatTargetDisplay(session: Session | undefined, targetId?: string, rawTarget?: string): Promise<string>;
    private getTargetRole;
    private createDryRunResult;
    planDemoAction(groupId: string, reason?: string): Promise<ActionResult>;
    kick(session: Session, target: string, rejectAddRequest?: boolean, reason?: string): Promise<ActionResult>;
    mute(session: Session, target: string, minutes: number, reason?: string): Promise<ActionResult>;
    unmute(session: Session, target: string, reason?: string): Promise<ActionResult>;
    setAdmin(session: Session, target: string, enable: boolean, reason?: string): Promise<ActionResult>;
}
